#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

# delete symlink bin command
rm /usr/bin/fclash || true

# delete desktop files
rm /usr/share/applications/cn.kingtous.fclash.desktop || true
if hash update-desktop-database 2>/dev/null; then
	update-desktop-database
fi

echo "fclash has successfully removed!"