name: fclash
base: core22
version: '1.4.0'
summary: A Linux Clash Proxy Fronted based on Clash # 79 char long summary
description: |
  A Linux Clash Proxy Fronted based on Clash. Supports subscriptions, proxies switcher, logger,
  dynamic settings, profile management, auto start with system.

grade: stable
confinement: strict
license: GPL-3.0+

architectures:
  - build-on: amd64
    build-for: amd64
#   - build-on: amd64
#     build-for: arm64

parts:
  fclash:
    plugin: nil
    source: .
    build-snaps: [go]
    override-build: |
      ./build-clash-lib.py
      git clone --depth 1 -b stable https://github.com/flutter/flutter.git /root/flutter
      export PATH="/root/flutter/bin:$PATH"
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/usr/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/usr/bin
    build-packages:
      - python3
      - git
      - curl
      - clang
      - cmake
      - ninja-build
      - unzip

apps:
  fclash:
    command: usr/bin/fclash
    extensions: [ gnome ]
    plugs:
      - network
      - home
      - unity7
      # manually connect by snap
      - system-observe
      - network-observe
      - network-control
      - network-status
      # end clash subprocess
      - process-control
